#spring.application.name=SpringBootAssignment
#spring.datasource.url=jdbc:mysql://localhost:3306/productdb

#spring.application.name=Application13
#spring.datasource.url=jdbc:mysql://localhost:3306/userdb

spring.application.name=Application14
spring.datasource.url=jdbc:mysql://localhost:3306/restaurantdb

spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update